Update status-check.yml

diff --git a/.github/workflows/status-check.yml b/.github/workflows/status-check.yml
--- a/.github/workflows/status-check.yml
+++ b/.github/workflows/status-check.yml
@@ -10,7 +10,9 @@ jobs:
 
     - name: Run tests
       id: tests # Reference used in the next job
-      run: echo "#Runing tests..."
+      run: |
+        echo "#Runing tests..."
+        exit 1 # Simulate failure
 
     - name: Check success status
       if: success()
